Improve test workflow / add deploy

diff --git a/.github/workflows/docker-publish-dotnet.yml b/.github/workflows/docker-publish-dotnet.yml
--- a/.github/workflows/docker-publish-dotnet.yml
+++ b/.github/workflows/docker-publish-dotnet.yml
@@ -43,3 +43,44 @@ jobs:
           tags: ${{ env.IMAGE_NAME }}
           cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
           cache-to: type=inline
+
+
+deploy-koyeb:
+  runs-on: ubuntu-latest
+  needs: build-and-push
+
+  steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Redeploy Service
+      env:
+        KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
+        IMAGE_NAME: ${{ env.IMAGE_NAME }}
+        SERVICE_ID: ${{ secrets.SERVICE_ID }}
+      run: |
+        #!/bin/bash
+        set -e
+
+        KOYEB_API_URL="https://app.koyeb.com/v1/services/${SERVICE_ID}/redeploy"
+
+        if [ -z "$KOYEB_API_TOKEN" ]; then
+          echo "KOYEB_API_TOKEN environment variable is not set"
+          exit 1
+        fi
+
+        PAYLOAD=$(echo '{"image": "'"$IMAGE_NAME"'"}')
+
+        RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X POST "$KOYEB_API_URL" \
+          -H "Authorization: Bearer $KOYEB_API_TOKEN" \
+          -H "Content-Type: application/json" \
+          -d "$PAYLOAD")
+
+        HTTP_STATUS=$(echo "$RESPONSE" | awk -F'HTTPSTATUS:' '{print $2}')
+
+        if [ "$HTTP_STATUS" -ne 200 ]; then
+          echo "Failed to trigger redeployment for service $SERVICE_ID. HTTP Status: $HTTP_STATUS"
+          exit 1
+        fi
+
+        echo "Successfully triggered redeployment for service $SERVICE_ID with image $IMAGE_NAME"
